language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "nightly"

# install os level dependencies
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
    - sudo apt-get install -qq libgmp-dev libmpfr-dev
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: make test
